package com.mitrian.diploma.voting.room.entity;

public enum WinnerSelectionPrinciple {
	NONE,
	STAGE_ONE_BASE_QUORUM_SINGLE,
	STAGE_TWO_RANK_SUM_UNIQUE_LEADER,
	STAGE_TWO_TIEBREAK_BY_APPROVAL_COUNT,
	STAGE_TWO_TIEBREAK_BY_ORGANIZER_RANK,
	STAGE_TWO_TIEBREAK_BY_STAGE_ONE_POSITION
}
