plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

def appMigrationsDir = file("${rootProject.projectDir}/app/src/main/resources/db/migration")

tasks.named('processResources', ProcessResources).configure {
	if (appMigrationsDir.exists()) {
		from(appMigrationsDir) {
			into('db/migration')
		}
	}
}

dependencies {
	implementation project(':voting')
	runtimeOnly 'org.postgresql:postgresql'
	implementation 'org.springframework.boot:spring-boot-starter-flyway'
	runtimeOnly 'org.flywaydb:flyway-database-postgresql'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-json'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	implementation platform('me.paulschwarz:spring-dotenv-bom:5.1.0')
	developmentOnly 'me.paulschwarz:springboot4-dotenv:5.1.0'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
}
